# Generated by Django 2.2.2 on 2019-06-29 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Plazo Fijo', 'Plazo Fijo'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Contrato'),
        ),
    ]
